In [1]:
import pandas as pd
import numpy as np
from faker import Faker

In [2]:
df = pd.read_csv('applicants.csv')

UNDERSTANDING THE DATA

In [3]:
df.shape

(80, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    79 non-null     object
 1   Email             79 non-null     object
 2   Phone             80 non-null     object
 3   Domain Applied    80 non-null     object
 4   University        78 non-null     object
 5   Application Date  80 non-null     object
 6   Status            79 non-null     object
dtypes: object(7)
memory usage: 4.5+ KB

In [5]:
df.head()

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Allison Hill,donaldgarcia@example.net,0351-2673502,Data Science,"Miller, Henderson and Johnson University",25/09/2026,Selected
1,Lance Hoffman,lrobinson@example.com,0298-2603453,Cybersecurity,Blake and Sons University,05/10/2026,Under Review
2,,curtis61@example.com,0528-7721409,Mobile App Dev,Munoz-Roman University,07/10/2026,Rejected
3,Valerie Gray,maria95@example.net,0577-5966374,web dev,Bush Inc University,2026-09-26,Under Review
4,Victoria Wyatt,jamesshawn@example.com,0349-1519402,UI/UX Design,Wood and Sons University,27/09/2026,Under Review

In [6]:
df.isnull().sum()

Applicant Name      1
Email               1
Phone               0
Domain Applied      0
University          2
Application Date    0
Status              1
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(2)

OBSERVATION: The data set has 80 rows, 7 columns. Applicant's name has 1 missing value, email has 1 missing value, 
university has 2 values, and status has 1 missing value

CLEANING THE DATA

In [8]:
#to find out the type of missing data I am working with
print(df[df['Applicant Name'].isna() == False]['Applicant Name'].unique())

['Allison Hill' 'Lance Hoffman' '   ' 'Valerie Gray' 'Victoria Wyatt'
 'Melinda Jones' 'Frederick Tate' 'Emily Rios' 'Nicole Patterson'
 'Christopher Becker' 'Kimberly Adams' 'Pamela Romero' 'Tammy Sellers'
 'John Jones' 'Tanya Campos' 'David Caldwell' 'Matthew Gomez' 'Ashley Lee'
 'Savannah Garcia' 'Stephanie Martin' 'Katelyn Lee' 'Kathryn Farrell'
 'Todd Hudson' 'James Powers' 'Brandi Bailey' 'Dr. Kendra Contreras'
 'Douglas Clark' 'Sandra Williams' 'Tony Vazquez' 'Christine Wright'
 'Rita Keith' 'Andrew Ruiz' 'Donald Jones' 'Victor Baker'
 'Cheryl Williams' 'Travis Mccall' 'Cheryl Ortega' 'Richard Lawson'
 'Diane Beck' 'Robert Contreras' 'Karen Green' 'Cynthia Rogers'
 'Joshua Perry' 'Guy Molina' 'George Shelton' 'Jeffrey Camacho'
 'Trevor Fisher' 'Tiffany Gonzalez' 'Carol Lawson' 'Tina Sanders'
 'Rebecca Knight' 'Samantha Garcia' 'Tamara Hampton' 'Jerry Christensen'
 'Spencer Haynes' 'Melissa Brewer' 'Jackie Tran' 'Patrick Tapia'
 'Elizabeth Ward' 'Beth Oneill' 'Dawn Hensley' 'Angela Wright'
 'Elizabeth Chapman' 'Brad Allen' 'Jordan Mcdaniel' 'Samantha Jones'
 'Terri Mason' 'Vernon Huff' 'Catherine Richards' 'Michael Roberts'
 'Jennifer Robertson' 'Olivia Harris' 'Michelle Collins'
 'Dr. Jordan Hill PhD' 'Desiree Tyler' 'Lauren Keller' 'Mrs. Janet Chase']

In [9]:
#turn empty strings into nan
#drop rows with no name
df['Applicant Name'] = df['Applicant Name'].replace('   ', np.nan)
df = df.dropna(subset=['Applicant Name'])

JUSTIFICATION: A record with no name lacks critical information needed to
identify the applicant

In [10]:
#fill rows with missing data with placeholder values
df['Email'] = df['Email'].fillna('None@example.com')
df['University'] = df['University'].fillna('Not Specified')
df['Status'] = df['Status'].fillna('Under Review')

In [11]:
df.duplicated().sum()

np.int64(2)

In [12]:
#drop duplicates
df = df.drop_duplicates()

In [13]:
#reset the index to avod inconsistencies in row labelling, since some rows were dropped
df = df.reset_index(drop=True)

In [14]:
df.head()

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Allison Hill,donaldgarcia@example.net,0351-2673502,Data Science,"Miller, Henderson and Johnson University",25/09/2026,Selected
1,Lance Hoffman,lrobinson@example.com,0298-2603453,Cybersecurity,Blake and Sons University,05/10/2026,Under Review
2,Valerie Gray,maria95@example.net,0577-5966374,web dev,Bush Inc University,2026-09-26,Under Review
3,Victoria Wyatt,jamesshawn@example.com,0349-1519402,UI/UX Design,Wood and Sons University,27/09/2026,Under Review
4,Melinda Jones,None@example.com,0790-4273183,Web Development,Nelson-Schaefer University,2026-10-12,Under Review

STANDARDISING DATA

In [15]:
#removing white spaces and standardise casing
df['Applicant Name'] = df['Applicant Name'].str.strip().str.title()

In [16]:
df['Domain Applied'].unique()

array(['Data Science', 'Cybersecurity', 'web dev', 'UI/UX Design',
       'Web Development', 'Mobile App Dev', 'WEB DEV', 'data-sci',
       'DATA SCI'], dtype=object)

In [17]:
domain_mapping = {
 'web dev': 'Web Development',
 'WEB DEV': 'Web Development',
 'web development': 'Web Development',
 'data-sci': 'Data Science',
   'DATA SCI': 'Data Science'
 }
df['Domain Applied'] = df['Domain Applied'].replace(domain_mapping)

In [18]:
df['Domain Applied'].unique()

array(['Data Science', 'Cybersecurity', 'Web Development', 'UI/UX Design',
       'Mobile App Dev'], dtype=object)

In [19]:
df['Status'].unique()

array(['Selected', 'Under Review', 'Rejected', 'selected'], dtype=object)

In [20]:
status_mapping= {
    'selected': 'Selected'
}
df['Status']= df['Status'].replace(status_mapping)

In [21]:
df['Status'].unique()

array(['Selected', 'Under Review', 'Rejected'], dtype=object)

In [22]:
df['Status'] = df['Status'].str.strip().str.title()

FIX DATA TYPES TO ENABLE PROPER CALCULATION ON THE DATA

In [23]:
df['Application Date']= pd.to_datetime(df['Application Date'], format='mixed', errors='coerce')

In [24]:
#phone number cleaning
df['Phone'] = df['Phone'].str.replace('-', '', regex=False).str.replace(' ', '', regex=False)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    76 non-null     object
 1   Email             76 non-null     object
 2   Phone             76 non-null     object
 3   Domain Applied    76 non-null     object
 4   University        76 non-null     object
 5   Application Date  76 non-null     datetime64[ns]
 6   Status            76 non-null     object
dtypes: datetime64[ns](1), object(6)
memory usage: 4.3+ KB

In [26]:
df['Phone']

0     03512673502
1     02982603453
2     05775966374
3     03491519402
4     07904273183
         ...
71    02047908599
72    07794887683
73    04689965859
74    07313929883
75    08878568428
Name: Phone, Length: 76, dtype: object

DATA QUALITY SUMMARY
The original data set has 80 rows, 7 columns
Issues found;
  - 5 missing vaues; 1 from Applicant's name, 1 from email, 2 from university and 1 from status
  - 2 duplicate values
  - Domain applied had 9 variations instead of 5 actual domain
  - Application date was stored as an object instead of an actual data
  - Status had 4 variations instead of 3 actual variations
  - Phone number contained inconsistent formatting

 Actions taken;
  - Dropped one row with no applicant;s name
  - Filled mising email values with None@example.com
  - Filled missing university values with Not specified
  - Filled missing status values with under review
  - Dropped 2 duplicate rows
  - Standardised casing and removed whitespaces on applicant's name column
  - Standardised all domain applied values into 5 unique categories
  - Standardised all status values into 3 unique categories
  - Standardised casing and removed whitespaces on status column
  - Converted application data to proper date time format
  - Cleaned phone number formatting

In [27]:
df.to_csv('applicants_cleaned.csv', index=False)

In [29]:
print(df['Application Date'].dtype)

datetime64[ns]